### ISSUE TITLE
error of npm ci 

### ISSUE THREAD

**Issue by skylonmiller** [dfinity/cycles-wallet#107]
Got below error info, when follow the instruction

```
➜  cycles vim  /Users/tom/.npm/_logs/2021-09-04T02_56_34_161Z-debug.log

0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'ci' ]
1 info using npm@7.6.1
2 info using node@v12.13.1
3 timing config:load:defaults Completed in 2ms 
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms 
5 timing config:load:builtin Completed in 2ms 
6 timing config:load:cli Completed in 2ms 
7 timing config:load:env Completed in 0ms 
8 timing config:load:file:/Volumes/macOSdat/backend/rustProject/crypt/dfinity/cycles/.npmrc Completed in 7ms 
9 timing config:load:project Completed in 25ms
10 timing config:load:file:/Users/tom/.npmrc Completed in 1ms 
11 timing config:load:user Completed in 1ms 
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms 
13 timing config:load:global Completed in 1ms 
14 timing config:load:cafile Completed in 0ms 
15 timing config:load:validate Completed in 3ms 
16 timing config:load:setUserAgent Completed in 0ms 
17 timing config:load:setEnvs Completed in 2ms 
18 timing config:load Completed in 39ms
19 verbose npm-session 159c9d1fdb01d7f7
20 timing npm:load Completed in 81ms
21 timing arborist:ctor Completed in 1ms 
22 timing npm-ci:rm Completed in 1ms 
23 verbose loadVirtual Error: loadVirtual requires existing shrinkwrap file
23 verbose loadVirtual     at Arborist.loadVirtual (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:57:18)
23 verbose loadVirtual     at async Promise.all (index 0)
23 verbose loadVirtual     at async CI.ci (/usr/local/lib/node_modules/npm/lib/ci.js:47:5)
24 timing command:ci Completed in 8ms 
25 verbose stack Error: The `npm ci` command can only install with an existing package-lock.json or
25 verbose stack npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
25 verbose stack later to generate a package-lock.json file, then try again.
25 verbose stack     at /usr/local/lib/node_modules/npm/lib/ci.js:54:15
25 verbose stack     at async Promise.all (index 0)
25 verbose stack     at async CI.ci (/usr/local/lib/node_modules/npm/lib/ci.js:47:5)
26 verbose cwd /Volumes/macOSdat/backend/rustProject/crypt/dfinity/cycles
27 verbose Darwin 19.6.0
28 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "ci"
29 verbose node v12.13.1
30 verbose npm  v7.6.1
31 error The `npm ci` command can only install with an existing package-lock.json or
31 error npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
31 error later to generate a package-lock.json file, then try again.
32 verbose exit 1
```

**Comment by skylonmiller** [comment]
cd cycles-wallet,  should be first step. Foolish...
